[build]
builder = "railpack/php"

# Tambahkan ekstensi ZIP agar Spatie Simple Excel bisa jalan
buildCommand = """
install-php-extensions zip
composer install --no-dev --optimize-autoloader
npm ci
npm run build
php artisan config:cache
php artisan route:cache
php artisan view:cache
"""

# Menjalankan Laravel di port yang disediakan Railway
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
